### ISSUE TITLE
Compatibility for Kodi 19 Matrix

### ISSUE THREAD

**Issue by steff75** [cranphin/kodi2mqtt#4]
Hello, I am using your fork of the mqtt addon. Thanks for that!  Would it be possible that you could make the addon compatible for Kodi 19 (Matrix)?

Thanks a lot!

**Comment by cranphin** [comment]
Hey, somehow missed this issue in my mail, I just updated my kodi to 19, so hopefully soon :D

**Comment by cranphin** [comment]
Well, it should work now, give it a try :)

**Comment by steff75** [comment]
Yes, it works again now. Thank you very much, I am very happy about it :) 👍

**Comment by cranphin** [comment]
Cool, nice someone else uses it :)

**Comment by gahujipo** [comment]
Just updated the installation to your fork. I confirm that it works again on Kodi Matrix. Thank you for maintaining this plugin.
